=begin
#FastAPI

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerStableDiffusionWebui::BodyDetectControlnetDetectPost
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SwaggerStableDiffusionWebui::BodyDetectControlnetDetectPost do
  let(:instance) { SwaggerStableDiffusionWebui::BodyDetectControlnetDetectPost.new }

  describe 'test an instance of BodyDetectControlnetDetectPost' do
    it 'should create an instance of BodyDetectControlnetDetectPost' do
      expect(instance).to be_instance_of(SwaggerStableDiffusionWebui::BodyDetectControlnetDetectPost)
    end
  end
  describe 'test attribute "controlnet_module"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "controlnet_input_images"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "controlnet_processor_res"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "controlnet_threshold_a"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "controlnet_threshold_b"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
