=begin
#FastAPI

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerStableDiffusionWebui::Request
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SwaggerStableDiffusionWebui::Request do
  let(:instance) { SwaggerStableDiffusionWebui::Request.new }

  describe 'test an instance of Request' do
    it 'should create an instance of Request' do
      expect(instance).to be_instance_of(SwaggerStableDiffusionWebui::Request)
    end
  end
end
