=begin
#FastAPI

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerStableDiffusionWebui::ResetBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SwaggerStableDiffusionWebui::ResetBody do
  let(:instance) { SwaggerStableDiffusionWebui::ResetBody.new }

  describe 'test an instance of ResetBody' do
    it 'should create an instance of ResetBody' do
      expect(instance).to be_instance_of(SwaggerStableDiffusionWebui::ResetBody)
    end
  end
  describe 'test attribute "session_hash"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "fn_index"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
