=begin
#FastAPI

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerStableDiffusionWebui::ValidationError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SwaggerStableDiffusionWebui::ValidationError do
  let(:instance) { SwaggerStableDiffusionWebui::ValidationError.new }

  describe 'test an instance of ValidationError' do
    it 'should create an instance of ValidationError' do
      expect(instance).to be_instance_of(SwaggerStableDiffusionWebui::ValidationError)
    end
  end
  describe 'test attribute "loc"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "msg"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
