language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build SwaggerStableDiffusionWebui.gemspec
  - gem install ./SwaggerStableDiffusionWebui-1.0.394ffa7b0a7fff3ec484bcd084e673a8b301ccc8.gem
