# -*- encoding: utf-8 -*-

=begin
#FastAPI

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "SwaggerStableDiffusionWebui/version"

Gem::Specification.new do |s|
  s.name        = "SwaggerStableDiffusionWebui"
  s.version     = SwaggerStableDiffusionWebui::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["KevinColemanInc"]
  s.email       = ["kevin@sparkstart.io"]
  s.homepage    = "https://github.com/KevinColemanInc/rb-swagger-stable-diffusion-webui"
  s.summary     = "FastAPI Ruby Gem"
  s.description = "No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
