=begin
#FastAPI

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

module SwaggerStableDiffusionWebui
  VERSION = '1.0.394ffa7b0a7fff3ec484bcd084e673a8b301ccc8'
end
